language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libhwloc-dev
  - git submodule update --init --recursive
before_script:
  - mkdir build && cd build && cmake ..
script: make && ./test/units
notifications:
  recipients:
    - sebastian.hillig@gmail.com
  email:
    on_success: change
    on_failure: always
