language: cpp
compiler_flag:
  - g++-4.7
  - g++-4.8
before_install:
  - git submodule update --init --recursive
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get install -qq libhwloc-dev
  - [[ $compiler_flag == "g++-4.7" ]] && sudo apt-get -qq install g++-4.7 && export CXX=g++-4.7 && export CC=gcc-4.7'
  - [[ $compiler_flag == "g++-4.8" ]] && sudo apt-get -qq install g++-4.8 && export CXX=g++-4.8 && export CC=gcc-4.8'
before_script:
  - mkdir build && cd build && cmake ..
script: make && ./test/units
notifications:
  recipients:
    - sebastian.hillig@gmail.com
  email:
    on_success: change
    on_failure: always
